root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build"
  bin = "./build/${APP_NAME}"
  full_bin = "APP_USER=air ./build/${APP_NAME}"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "build", ".github", ".vscode"]
  log = "air.log"
  delay = 0 # ms

[log]
  # Show log time
  time = true
  # Only show main log (silences watcher, build, runner)
  main_only = false
  # silence all logs produced by air 
  silent = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true

[color]
  # Customize each part's color. If no color found, use the raw app log.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[proxy]
  # Enable live-reloading on the browser.
  enabled = true
  proxy_port = 8090
  app_port = 8080